export const Types = {
    SEARCHBARVISIBLE : "SEARCHBARVISIBLE",
    CHANGEURI : "CHANGEURI",
    CHANGEITEMUSER: "CHANGEITEMUSER",
    CHANGEITEMCLIENT: "CHANGEITEMCLIENT",
    SIGN_IN: "SIGN_IN",
    RESTORE_TOKEN: "RESTORE_TOKEN"
    
}
